# Generated by Django 3.2.4 on 2023-02-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_student_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('sesion_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.session')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AttendenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('attendence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attendence')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subject')),
            ],
        ),
    ]
